### PR TITLE
Fix bug when inserting previously deleted documents

### LINKED ISSUE #268: Critical issue when adding/deleting documents
Le Petit Prince is back, but without Antoine de Saint Exupéry this time!

- Add this documents:
```json
[
    { "objectId": 123,  "title": "Pride and Prejudice",                    "comment": "A great book" },
    { "objectId": 456,  "title": "Le Petit Prince",                        "comment": "A french book" },
    { "objectId": 1,    "title": "Alice In Wonderland",                    "comment": "A weird book" },
    { "objectId": 30,    "title": "Hamlet" }
]
```

- Delete the document 30
- Add this documents 3 times
```json
[
    { "objectId": 30,    "title": "Hamlet" }
]
```
- Get all documents: the document 30 appears three times
- Try to get the document 30 -> an error is raised, the document is not found

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR fixes #268.

The issue was in the `ExternalDocumentsIds` implementation in the specific case that an external document id was in the soft map marked as deleted.

The bug was due to a wrong assumption on my side about how the FST unions were returning the `IndexedValue`s, I thought the values returned in an array were in the same order as the FSTs given to the `OpBuilder` but in fact, [the `IndexedValue`'s `index` field was here to indicate from which FST the values were coming from](https://docs.rs/fst/0.4.7/fst/map/struct.IndexedValue.html).

### CODE REVIEW

File: milli/src/external_documents_ids.rs [hunk 1]
```diff
@@ -32,7 +37,7 @@ impl<'a> ExternalDocumentsIds<'a> {
         let external_id = external_id.as_ref();
         match self.soft.get(external_id).or_else(|| self.hard.get(external_id)) {
             // u64 MAX means deleted in the soft fst map
```
Comment (irevoire) [inline milli/src/external_documents_ids.rs:39]:
```suggestion
```
I guess we can delete this line now

File: milli/src/external_documents_ids.rs [hunk 2]
```diff
@@ -112,6 +141,15 @@ impl Default for ExternalDocumentsIds<'static> {
     }
 }
 
+/// Returns the value of the `IndexedValue` with the highest _index_.
+fn indexed_last_value(indexed_values: &[IndexedValue]) -> Option<u64> {
+    indexed_values
+        .iter()
+        .copied()
+        .reduce(|a, b| cmp::max_by_key(a, b, |iv| iv.index))
```
Comment (irevoire) [inline milli/src/external_documents_ids.rs:149]:
```suggestion
        .max_by_key(|iv| iv.index)
```
Can't we do that here?

File: milli/src/external_documents_ids.rs (hunk 1 above)
Comment (Kerollmops) [reply milli/src/external_documents_ids.rs:39]: That's right!

File: milli/src/external_documents_ids.rs (hunk 2 above)
Comment (Kerollmops) [reply milli/src/external_documents_ids.rs:149]: That's absolutely right, maybe I am redeclaring the internal algorithm inside `Iterator::max_by_key` :)

**Review by irevoire — APPROVED** [review]

**Comment by Kerollmops** [comment]
Thank you @irevoire.
bors merge
