### PR TITLE
Fix primary key behavior

### LINKED ISSUE #194: Wrong primary key returned when doing inference
Transplant does not return the correct primary key when doing inference during document addition.

Example:

Add this documents
```json
[
  { "objectId": 2, "title": "Pride and Prejudice" }
]
```

Should give me this result when I get the index info:

```json
{
    "uid": "indexUID",
    "name": "indexUID",
    "createdAt": "2021-04-27T15:41:13.439646200Z",
    "updatedAt": "2021-04-27T15:41:23.465335700Z",
    "primaryKey": "objectId"
}
```

But I get:
```
{
    "uid": "indexUID",
    "name": "indexUID",
    "createdAt": "2021-04-27T15:41:13.439646200Z",
    "updatedAt": "2021-04-27T15:41:23.465335700Z",
    "primaryKey": "id"
}
```

Version: alpha4

### PR DESCRIPTION
**Pull request by MarinPostma**
this pr:
- Adds early returns on empty document additions, avoiding error messages to be returned when adding no documents and no primary key was set.
- Changes the primary key inference logic to match that of legacy meilisearch.

close #194

### CODE REVIEW

**Comment by MarinPostma** [comment]
closes #194

File: milli/src/update/index_documents/mod.rs [hunk 1]
```diff
@@ -326,6 +326,16 @@ impl<'t, 'u, 'i, 'a> IndexDocuments<'t, 'u, 'i, 'a> {
...
+        let mut reader = BufReader::new(reader);
+        reader.fill_buf()?;
+
+        // Early return when there is no document to add
+        if reader.buffer().is_empty() {
+            return Ok(DocumentAdditionResult {
+                nb_documents: 0,
+            })
+        }
+
```
Comment (Kerollmops) [inline milli/src/update/index_documents/mod.rs:338]: Is it a way to make sure that we do not create a default primary key that is "id" because no documents (and therefore no primary key) were found?

Comment (MarinPostma) [reply milli/src/update/index_documents/mod.rs:338]: No, it's a way to not throw a "could not infer primary key" on an empty addition 🙂

Comment (MarinPostma) [reply milli/src/update/index_documents/mod.rs:338]: Or is it? 🤔 I'm tired, maybe I understood @irevoire issue wrong

Comment (irevoire) [reply milli/src/update/index_documents/mod.rs:338]: Yeah that was my issue

Comment (MarinPostma) [reply milli/src/update/index_documents/mod.rs:338]: Tell me if this solves it ☺️ (next week)

File: milli/src/update/index_documents/transform.rs [hunk 2]
```diff
@@ -92,7 +96,7 @@ impl Transform<'_, '_> {
         // We extract the primary key from the first document in
         // the batch if it hasn't already been defined in the index
         let first = documents.peek().and_then(|r| r.as_ref().ok());
```
Comment (Kerollmops) [inline milli/src/update/index_documents/transform.rs:98]: I found this line to make the engine return an error that is not the right one, when there is a decoding error we simply ignore it (`.ok()`), and then this a "missing primary key" error that is thrown due to the fact that no primary key was guessed **and** that the `alternate_name` is None because the first document is invalid.

We should early return when we find that the first document is erroneous, it would be better, but the error doesn't impl `Clone` so we can't return it from the `peek`. We should check that the peeked document is `Err` and if it is we should next and return the error (`unwrap_err`).

File: milli/src/update/index_documents/transform.rs [hunk 3]
```diff
@@ -92,7 +96,7 @@ impl Transform<'_, '_> {
...
-        let alternative_name = first.and_then(|doc| doc.keys().find(|k| k.contains(DEFAULT_PRIMARY_KEY_NAME)).cloned());
+        let alternative_name = first.and_then(|doc| doc.keys().find(|f| is_primary_key(f)).cloned());
```
Comment (Kerollmops) [inline milli/src/update/index_documents/transform.rs:99]:
```suggestion
        let alternative_name = first.and_then(|doc| doc.keys().find(is_primary_key).cloned());
```

File: milli/src/update/index_documents/transform.rs [hunk 4]
```diff
@@ -232,7 +236,7 @@ impl Transform<'_, '_> {
                // The primary key is known so we must find the position in the CSV headers.
                headers.iter().position(|h| h == primary_key)
             },
-            None => headers.iter().position(|h| h.contains("id")),
+            None => headers.iter().position(|f| is_primary_key(&f)),
```
Comment (Kerollmops) [inline milli/src/update/index_documents/transform.rs:239]:
```suggestion
            None => headers.iter().position(is_primary_key),
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]

File: milli/src/update/index_documents/transform.rs (hunk 2 above)
Comment (LegendreM) [reply milli/src/update/index_documents/transform.rs:98]:
```suggestion
        let first = match iter.peek() {
            Some(Err(_)) => iter.next().transpose()?,
            Some(Ok(x)) => Some(x),
            None => None,
        };
```

Untested in this context

**Review by ManyTheFish — DISMISSED** [review]

File: milli/src/update/index_documents/mod.rs (hunk 1 above)
Comment (MarinPostma) [reply milli/src/update/index_documents/mod.rs:338]: I have a client side fix for this, but I am not sure whose duty it is to do that, milli's or the clien?

Comment (Kerollmops) [reply milli/src/update/index_documents/mod.rs:338]: But doesn't this commit fix the issue, here?

Comment (MarinPostma) [reply milli/src/update/index_documents/mod.rs:338]: yes but I ended up implementing a fix in dumps so we could merge it. We can leave it here, and 'll remove it from dumps. The question is, should you get an error for pushing an empty document addition or not? I claim that we shouldn't, but I wanted to know if you thought otherwise.

File: milli/src/update/index_documents/transform.rs (hunk 3 above)
Comment (MarinPostma) [reply milli/src/update/index_documents/transform.rs:99]: not possible, f is a &&String, and rustc doesn't like it.

File: milli/src/update/index_documents/transform.rs (hunk 2 above)
Comment (MarinPostma) [reply milli/src/update/index_documents/transform.rs:98]: this doesn't compile, but I wrote something similar.

File: milli/src/update/index_documents/mod.rs (hunk 1 above)
Comment (Kerollmops) [reply milli/src/update/index_documents/mod.rs:338]: You must not get an error if you push an empty update, that's valid, even for the first update (where we guess the primary key).

File: milli/src/update/index_documents/transform.rs [hunk 5]
```diff
@@ -91,8 +95,12 @@ impl Transform<'_, '_> {
 
         // We extract the primary key from the first document in
         // the batch if it hasn't already been defined in the index
-        let first = documents.peek().and_then(|r| r.as_ref().ok());
-        let alternative_name = first.and_then(|doc| doc.keys().find(|k| k.contains(DEFAULT_PRIMARY_KEY_NAME)).cloned());
+        let first = match documents.peek().map(Result::as_ref).transpose() {
+            Ok(first) => first,
+            Err(_) => return Err(documents.next().unwrap().unwrap_err().into()),
+
```
Comment (Kerollmops) [inline milli/src/update/index_documents/transform.rs:101]: As we know this is an error we can reduce a little bit the `unwrap`s + `return`s boilerplate.

```suggestion
            Err(_) => documents.next().unwrap()?,
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]
That's fine, thank you for your PR, I merge it after these little changes are applied :)
Thank you!

File: milli/src/update/index_documents/transform.rs (hunk 5 above)
Comment (MarinPostma) [reply milli/src/update/index_documents/transform.rs:101]: that is not gonna work, the first branch is a ref, and next returns a owned

Comment (Kerollmops) [reply milli/src/update/index_documents/transform.rs:101]: Ho yeah, you are right, my badu!

Comment (Kerollmops) [reply milli/src/update/index_documents/transform.rs:101]: But please remove this newline :)

**Review by Kerollmops — APPROVED** [review]
Thank you very much, merging 😃
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge

**Comment by Kerollmops** [comment]
bors merge
