### PR TITLE
Make hard separators split phrase query

### LINKED ISSUE #208: Phrase Query behavior
I have just tested the Phrase Query syntax on an updated 0.21 build and I have behaviors that seem unwanted. I can provide the dataset used if needed to reproduce the tests! Thanks!

# Tests Phrase Query

## Test case 1: Case sensivity

> "q": "\"the four seasons: Poems\""

### Results

```
"hits": [
    {
        "title": "The Four Seasons: Poems",
        "author": "J. D. McClatchy"
    }
]
```

### case 2.1

> "q": "\"African American Literature\"" OR "q": "\"African-American Literature\""

### Results
Same results for the 2 queries
```
{
    "title": "African American Literature (Penguin Academics Series)",
    "author": "Keith Gilyard"
},
{
    "title": "African-American Literature: A Brief Introduction and Anthology",
    "author": "Al Young"
},
{
    "title": "A Companion to African American Literature",
    "author": "Gene A. Jarrett"
}
```

### Results
```
"hits": [
    {
        "title": "The Four Seasons: Poems",
        "author": "J. D. McClatchy"
    }
]
```

Weird case because i have no result besides that title exists
My first guess was because the query was too long. But it's not that because it worked with a long title on another document.
My guess is that's because of `(`or ) characters.

### Results

None

### PR DESCRIPTION
**Pull request by ManyTheFish**
hard separators will now split a phrase query as two sequential phrases (double-quoted strings):

the query `"Radioactive (Imagine Dragons)"` would be considered equivalent to `"Radioactive" "Imagine Dragons"` which as the little disadvantage of not keeping the order of the two (or more) separate phrases.

Fix #208

### CODE REVIEW

File: milli/src/search/query_tree.rs [hunk 1]
```diff
@@ -467,13 +469,14 @@ fn create_primitive_query(query: TokenStream, stop_words: Option<Set<&[u8]>>, wo
...
             },
-            TokenKind::Separator(_) => {
+            TokenKind::Separator(separator_kind) => {
                 let quote_count = token.word.chars().filter(|&s| s == '"').count();
                 // swap quoted state if we encounter a double quote
                 if quote_count % 2 != 0 {
                     quoted = !quoted;
                 }
-                if !phrase.is_empty() && quote_count > 0 {
+                // if there are any quote or any hard separator we close the phrase.
```
Comment (Kerollmops) [inline milli/src/search/query_tree.rs:478]:
```suggestion
                // if there is a quote or a hard separator we close the phrase.
```

**Review by Kerollmops — CHANGES_REQUESTED** [review]

**Review by Kerollmops — APPROVED** [review]
Thank you!
bors merge
