### PR TITLE
Fix facet distribution error

### LINKED ISSUE #253: Should raise error when trying `facetsDistribution` on a non-filterable attribute
When doing a search with `facetsDistribution` on a non-filterable attribute, I get an empty object.

We should raise an error to warn the user

### PR DESCRIPTION
**Pull request by Kerollmops**
This PR fixes two invalid behaviors and fixes #253:
 - We were ignoring the list of fields for which the user wanted a facet distribution.
 - We were not raising any error for when a non-filterable field was requested a facet distribution.

~For the latter behavior I need the help of @curquiza to help me choose the right error type.~

### CODE REVIEW

File: milli/src/search/facet/facet_distribution.rs [hunk 1]
```diff
@@ -174,49 +174,61 @@ impl<'a> FacetDistribution<'a> {
...
     }
 
     pub fn execute(&self) -> Result<BTreeMap<String, BTreeMap<String, u64>>> {
         let fields_ids_map = self.index.fields_ids_map(self.rtxn)?;
         let filterable_fields = self.index.filterable_fields(self.rtxn)?;
+        let fields = match self.facets {
+            Some(ref facets) => {
+                let invalid_fields: HashSet<_> = facets.difference(&filterable_fields).collect();
+                if !invalid_fields.is_empty() {
+                    todo!("return an error specifying that these fields are not filterable");
```
Comment (Kerollmops) [inline milli/src/search/facet/facet_distribution.rs:222]: @curquiza Help me choose the right error to raise here, please :)

**Review by curquiza — APPROVED** [review]
👌

**Comment by Kerollmops** [comment]
bors merge
